# Generated by Django 3.2.9 on 2021-11-09 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_like_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like_blog',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
