# Generated by Django 3.2.9 on 2021-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blog_like_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='AnonymousEmailId', max_length=254),
        ),
    ]
