# Generated by Django 3.2.9 on 2021-11-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20211112_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like_for',
        ),
        migrations.DeleteModel(
            name='Unique_user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post_category',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
