# Generated by Django 3.2.9 on 2021-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20211116_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_title',
            field=models.CharField(default='BIO-GRAPHY', max_length=3000),
        ),
    ]
