# Generated by Django 3.2.9 on 2021-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_blog_main_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
